install.packages("tidyverse")
install.packages("knitr")
install.packages("remotes")
install.packages("moderndive")
install.packages("plotly")
install.packages("RColorBrewer")
install.packages("rmarkdown")
install.packages("babynames")
install.packages("hrbrthemes")
install.packages("htmltools")
# install.packages("broom")
install.packages("countdown")
install.packages("skimr")
install.packages("patchwork")
