---
title: "R for Computational Sciences"
subtitle: "Part 2.  Viz, pivot, join, models"
author: "John Little"
institute: "Center for Data & Vizualization Sciences"
params: 
  workshop_date: "Sept. 22"
  workshop_time: "1-3pm"
  registered: 62
  goog_sheet_pre_workshop: "https://docs.google.com/spreadsheets/d/1s1AMfjeU76N56zwY521pVMUX0VoxL6WHZBT2c_3L4bM/edit#gid=275920804"
  countdown_minutes: 20
output:
  xaringan::moon_reader:
    css: 
      - mystyles/xaringan-themer.css          # fonts https://pkg.garrickadenbuie.com/xaringanthemer/articles/xaringanthemer.html
      - mystyles/adirondack/story.css         # https://story.xaprb.com/slides/adirondack/
      - mystyles/adirondack/apron.css         # layout     
      - mystyles/adirondack/descartes.css     # image positon 
      - mystyles/adirondack/tachyons.min.css  # color, font weights, boxes        
      - styles/my-theme.css 
    lib_dir: libs
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(gt)
library(lubridate)
library(hrbrthemes)
library(xaringanthemer)
library(xaringanExtra)
xaringanExtra::use_tachyons()
library(countdown)
library(googlesheets4)
library(htmltools)
tagList(rmarkdown::html_dependency_font_awesome())
```

```{r themes, warning=FALSE, include=FALSE}
style_duo_accent(primary_color = "#012169", secondary_color = "#005587")

pre_workshop <- read_sheet(params$goog_sheet_pre_workshop)
# post_workshop <-
#   read_sheet("https://docs.google.com/spreadsheets/d/18-xeU5YAOr0iu7Pk22Zrb0BziLuoVe8nyCyd1-O2R7U/edit#gid=123486400")


mynames_pre  <- read_csv("data/colnames_part1_preworkshop_2021fall.csv")
mynames_post <- read_csv("data/colnames_part1_postworkshop_2021fall.csv")

colnames(pre_workshop) <- mynames_pre$value
# colnames(post_workshop) <- mynames_post$value

pre_workshop <- pre_workshop %>%
  mutate(survey_type = "pre")
# post_workshop <- post_workshop %>%
#   mutate(survey_type = "post") 

```

