---
title: "Compare Pre/post"
author: "John Little"
---


```{r}
library(tidyverse)
library(lubridate)
library(hrbrthemes)
library(googlesheets4)
```




```{r}
# pre_workshop 
# post_workshop 

pre_workshop <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1pbW7altQx4mF5C2CZBvwQEnGEeLKnyXM-LG89cHp1Xo/edit#gid=1628675293")
post_workshop <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1QsSpx4VT4gETSe4olAVy6lBj-KhvdSPpD5Xkd9kBTso/edit#gid=342600337")
```


```{r}
colnames(pre_workshop)
colnames(post_workshop)
```

```{r}
mynames_pre <- read_csv("data/colnames_part2_preworkshop.csv")
mynames_post <- read_csv("data/colnames_part2_postworkshop.csv")

colnames(pre_workshop) <- mynames_pre$value
colnames(post_workshop) <- mynames_post$value

pre_workshop <- pre_workshop %>%
  mutate(survey_type = "pre")
post_workshop <- post_workshop %>% 
  filter(!str_detect(search4answers, "NOTE")) %>% 
  mutate(survey_type = "post") %>% 
  select(-what_worked, -continue_curriculum, -add_curriculum)
```


```{r}
pre_workshop
post_workshop
```



```{r}
survey_df <- bind_rows(pre_workshop, post_workshop)
survey_df
```

```{r}
survey_df <- survey_df %>% 
  select(Timestamp, import_data:join, survey_type) 
survey_df
```

```{r}
response_rate <- nrow(pre_workshop) / 60

pre_workshop %>% 
  filter(survey_type == "pre") %>% 
  mutate(day = lubridate::yday(Timestamp)) %>%
  count(day) %>% 
  ggplot(aes(day, n)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(minor_breaks = NULL) +
  scale_x_continuous(minor_breaks = NULL, 
                     breaks = seq(246, 253, 1),
                     labels = c("Wed", "Thu", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed")) +
  ylim(0,6) +
  labs(title = "Response rate over time",
       subtitle = "n = 19 ; Resposne rate: 32%", y = "",
       caption = "Source:  CDVS Pre-workshop survey") 
```

```
{r}
pre_workshop %>%
  pivot_longer(coder:shell_cli, names_to = "question", values_to = "answer") %>% 
  mutate(question = factor(question, levels = c("rdbms", "shell_cli", 
                                                "version_control", "models", "coder"))) %>% 
  mutate(answer = factor(answer, levels = c("Daily", "Weekly", "Monthly",
                                            "Several Times per year",
                                            "Less than once per year",
                                            "Never"))) %>% 
  ggplot(aes(question)) +
  geom_bar(aes(fill = answer), position = "fill") +
  coord_flip() +
  scale_fill_brewer(palette = "Dark2") +
  labs(title = "Self-reported tool usage",
       subtitle = "Respondent's use of a tool / technology / technique",
       x = "", y = "Percent",
       caption = "Source:  CDVS Pre-workshop survey") +
  # theme(plot.title.position = "plot")
  theme_ipsum(grid = "X")
```

```{r fig.height=7, fig.width=12, message=FALSE, warning=FALSE}
# form_data %>% # import, edit, subset, project, repro, apply, answer tech, overcome probs
survey_df %>% 
  mutate(survey_type = case_when(
    survey_type == "pre" ~ "Pre-workshop survey",
    survey_type == "post" ~ "Post-workshop survey"
  )) %>% 
  pivot_longer(make_plots:join, 
               names_to = "question", 
               values_to = "answer") %>% 
  mutate(answer = if_else(answer == "Strongly Agree", "Strongly agree", answer)) %>% 
  mutate(answer = factor(answer, 
                         levels = c("Strongly agree", "Agree", 
                                    "Neutral", "Disagree", 
                                    "Strongly disagree"))) %>%
  mutate(question  = factor(question,
                            levels = c(#"import_data", "edit_scripts",
                                       "make_plots", "ggplot2",
                                       "interactive", "pivot",
                                       "join"))) %>%
  ggplot(aes(fct_rev(question))) +
  geom_bar(aes(fill = answer), position = "fill") +
  coord_flip() +
  facet_wrap(~ fct_rev(survey_type), dir = "v") +
  scale_fill_brewer(palette = "Spectral") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Self-reported R skills",
       subtitle = "Respondent feels capable of completing a Tidyverse task",
       x = "", y = "",
       caption = "Source:  Pre & Post workshop surveys",
       fill = "") +
  theme_ipsum(grid = "X") +
  theme(plot.title.position = "plot")
```

```{r}
ggsave("images/pre_post_survey.svg", width = 12, height = 7)
```



```{r fig.height=5, fig.width=12, message=FALSE, warning=FALSE}
survey_df %>% 
  mutate(survey_type = case_when(
    survey_type == "pre" ~ "Pre-workshop",
    survey_type == "post" ~ "Post-workshop"
  )) %>% 
  select(survey_type, make_plots:join) %>% 
  pivot_longer(make_plots:join, 
               names_to = "question", 
               values_to = "answer") %>% 
  mutate(answer = if_else(answer == "Strongly Agree", "Strongly agree", answer)) %>% 
  mutate(answer = factor(answer, 
                         levels = c("Strongly agree", "Agree", 
                                    "Neutral", "Disagree", 
                                    "Strongly disagree"))) %>%
  mutate(question  = factor(question,
                            levels = c(#"import_data", "edit_scripts",
                                       "make_plots", "ggplot2",
                                       "interactive", "pivot",
                                       "join"))) %>%
  ggplot(aes(fct_rev(question), fill = survey_type)) +
  geom_bar(position = "fill") +
  coord_flip() +
  scale_fill_manual(values = c("dark orange", "gray63")) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~ answer, nrow = 1) +
  guides(fill = guide_legend(reverse = TRUE)) + #FALSE) 
  labs(title = "Self-reported R skills",
       subtitle = "Respondents feel capable of completing a Tidyverse task",
       x = "", y = "", fill = "Suvey",
       caption = "Source:  Pre & Post workshop surveys",
       fill = "") +
  theme_ipsum(grid = "X") +
  theme(plot.title.position = "plot", legend.position = "top")
```
        

```{r}
ggsave("images/pre_post_survey2.svg", width = 12, height = 5)
```


```{r}
survey_df %>% 
  mutate(survey_type = case_when(
    survey_type == "pre" ~ "Pre-workshop survey",
    survey_type == "post" ~ "Post-workshop survey"
  )) %>% 
  pivot_longer(make_plots:join, 
               names_to = "question", 
               values_to = "answer") %>% 
  mutate(answer = if_else(answer == "Strongly Agree", "Strongly agree", answer)) %>% 
  mutate(answer = factor(answer, 
                         levels = c("Strongly agree", "Agree", 
                                    "Neutral", "Disagree", 
                                    "Strongly disagree"))) %>%
  mutate(question  = factor(question,
                            levels = c(#"import_data", "edit_scripts",
                                       "make_plots", "ggplot2",
                                       "interactive", "pivot",
                                       "join"))) %>%
  ggplot(aes(fct_rev(question), fill = answer, group = survey_type)) +
  geom_bar(position = position_dodge2()) 
```


```{r fig.width=12}
survey_df %>% 
  mutate(survey_type = case_when(
    survey_type == "pre" ~ "Pre-workshop survey",
    survey_type == "post" ~ "Post-workshop survey"
  )) %>% 
  select(survey_type, make_plots:join) %>% 
  pivot_longer(make_plots:join, 
               names_to = "question", 
               values_to = "answer") %>% 
  mutate(answer = if_else(answer == "Strongly Agree", "Strongly agree", answer)) %>% 
  mutate(answer = factor(answer, 
                         levels = c("Strongly agree", "Agree", 
                                    "Neutral", "Disagree", 
                                    "Strongly disagree"))) %>%
  mutate(question  = factor(question,
                            levels = c(#"import_data", "edit_scripts",
                                       "make_plots", "ggplot2",
                                       "interactive", "pivot",
                                       "join"))) %>%
  ggplot(aes(fct_rev(question), fill = survey_type)) +
  geom_bar(position = "dodge2") +
  coord_flip() +
  scale_fill_manual(values = c("forest green", "firebrick")) +
  facet_wrap(~ answer, nrow = 1) +
  guides(fill = FALSE) #guide_legend(reverse = TRUE))
```



