install.packages("tidyverse")
install.packages("googlesheets4")
install.packages("knitr")
install.packages("remotes")
install.packages("moderndive")
install.packages("plotly")
install.packages("RColorBrewer")
install.packages("rmarkdown")
install.packages("babynames")
install.packages("hrbrthemes")
install.packages("htmltools")
install.packages("xaringan")
install.packages("broom")
remotes::install_github("gadenbuie/xaringanthemer")
remotes::install_github("gadenbuie/xaringanExtra")
remotes::install_github("thomasp85/patchwork")
remotes::install_github("skimr")
remotes::install_github("countdown")
#  "glue",
#  "scales",
# install.packages("lubridate")
# install.packages("devtools")
